config/routes.rb
Rails.application.routes.draw do
  #get 'sessions/create'

  #get 'sessions/destroy'

  #get 'home/show'
  
get 'auth/:provider/callback', to: 'sessions#create'
get 'auth/failure', to: redirect('/')
get 'signout', to: 'sessions#destroy', as: 'signout'
 
resources :sessions, only: [:create, :destroy]
resource :home, only: [:show]
 
root to: "home#show"

end

app/models/user.rb
    class User < ActiveRecord::Base
    def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.oauth_token = auth.credentials.token
    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    user.save!
    end
    end
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   helper_method :current_user
 
def current_user
@current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
    class SessionsController < ApplicationController
    def create
    
	user=request.env["omniauth.auth"]
   
	#	graph = Koala::Facebook::GraphAPI.new(@access)
#friends = graph.get_connections("user", "friends")
#graph.put_object("user", "feed", :message => "I am writing on my wall!")
  @image=user["info"]["image"]
  @name=user["info"]["name"]
  @access= user["credentials"]["token"]
  @graph = Koala::Facebook::GraphAPI.new(@access)

  @graph.put_wall_post("I'm writing on my wall(ruby testing) :)")

#render :text => @graph.get_object("me")


 user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
   # redirect_to root_path
    end
     
    def destroy
    session[:user_id] = nil
    redirect_to root_path
    end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/show.html.erb
<!--
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>
 
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookAuth</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1 align ="center"><font color="red">//Facebook Authentication using Ruby On Rails4//</font> </h1>
<div id="user_nav">
  <% if current_user %>
  <center>  Signed in as <strong><%= current_user.name %></strong>!<br>
    <%= link_to "Click here to Sign out", signout_path, id: "sign_out" %></center>
  <% else %>
  <center>  <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></center>
    
  <% end %>

</div>
<%= yield %>
<center><h2><font color="red"> Profile Picture <br></font></2><img src="<%= @image %>"/></center>
  
</body>
</html>